package com.zwyft.horizon.service

import android.content.Context
import com.zwyft.horizon.data.HorizonDatabase
import com.zwyft.horizon.data.entity.MessageEntity
import com.zwyft.horizon.repository.ContactRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.UUID

/**
 * Orchestrates a full message sync:
 *  1. Reads historical SMS via [SmsMessageReader]
 *  2. Inserts them into the Room database (idempotent on `messageId` unique index)
 *  3. Matches each message against monitored contacts and flips `monitored = true`
 *
 * RCS messages are NOT read historically — Android does not expose RCS to third
 * parties. New RCS messages are caught by [NotificationListener] / [MessageCaptureService].
 */
class MessageSyncManager(
    private val context: Context,
    private val db: HorizonDatabase
) {
    companion object {
        const val SYNC_BATCH_TAG = "sms_sync"
    }

    sealed class Result {
        data class Success(val imported: Int, val matched: Int) : Result()
        data class PermissionDenied(val permission: String) : Result()
        data class Error(val message: String) : Result()
    }

    /**
     * Run a one-shot sync.
     *
     * @param sinceMillis If non-null, only sync messages newer than this. Pass null to
     *                    re-read everything (Room's `OnConflictStrategy.IGNORE` keeps
     *                    the operation idempotent).
     * @param limit       Cap on messages read per call (per box).
     */
    suspend fun syncMessages(
        sinceMillis: Long? = null,
        limit: Int = 5000
    ): Result = withContext(Dispatchers.IO) {
        val reader = SmsMessageReader(context)

        if (!reader.hasPermission()) {
            return@withContext Result.PermissionDenied("READ_SMS")
        }

        try {
            val batchTag = "$SYNC_BATCH_TAG-${UUID.randomUUID()}"

            // 1. Read SMS from system provider
            val smsMessages = reader.readAll(
                sinceMillis = sinceMillis,
                batchTag = batchTag,
                limit = limit
            )

            // 2. Read MMS from system provider. Uses the same
            //    READ_SMS permission (verified via MmsPermissionHelper).
            //    Failures here are non-fatal — SMS is the dominant
            //    case, and we don't want to break SMS if MMS is broken.
            val mmsResults = try {
                MmsReader(context).readAll(
                    sinceMillis = sinceMillis,
                    batchTag = batchTag,
                    limit = (limit / 10).coerceAtLeast(100) // MMS less frequent
                )
            } catch (e: Exception) {
                android.util.Log.w("MessageSyncManager", "MMS read failed, continuing with SMS only", e)
                emptyList()
            }

            if (smsMessages.isEmpty() && mmsResults.isEmpty()) {
                return@withContext Result.Success(0, 0)
            }

            // 3. Insert SMS into Room (IGNORE on conflict = safe re-sync)
            if (smsMessages.isNotEmpty()) {
                db.messageDao().insertAll(smsMessages)
            }

            // 4. Insert MMS messages and their attachments. We do this
            //    in two steps: insert all messages first to get their
            //    generated row ids, then backfill the messageId on each
            //    attachment and insert attachments in a second batch.
            //    (Room's FK is enforced but the id is autoGenerated, so
            //    we need the parent's id before the child can reference it.)
            if (mmsResults.isNotEmpty()) {
                val mmsMessages = mmsResults.map { it.message }
                val mmsIds = db.messageDao().insertAll(mmsMessages)
                val attachDao = db.messageAttachmentDao()
                val pendingAttachments = mutableListOf<com.zwyft.horizon.data.entity.MessageAttachmentEntity>()
                mmsResults.forEachIndexed { i, res ->
                    val newId = mmsIds.getOrNull(i)
                    if (newId != null && newId != -1L) {
                        res.attachments.forEach { a ->
                            pendingAttachments += a.copy(messageId = newId)
                        }
                    }
                }
                if (pendingAttachments.isNotEmpty()) {
                    attachDao.insertAll(pendingAttachments)
                }
            }

            // 5. Auto-create contacts from top addresses if none exist,
            //    then always re-match every message (handles 2nd+ syncs)
            val repo = ContactRepository(db)
            repo.seedDefaults()
            repo.recomputeAllMonitored()

            // 6. Count how many messages are now monitored
            val monitoredCount = db.messageDao().countMonitored()

            Result.Success(smsMessages.size + mmsResults.size, monitoredCount)
        } catch (e: Exception) {
            e.printStackTrace()
            Result.Error(e.message ?: "Unknown error during sync")
        }
    }


}
