package com.zwyft.horizon.export

import android.content.Context
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.AreaBreak
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.UnitValue
import com.zwyft.horizon.data.HorizonDatabase
import com.zwyft.horizon.data.entity.MessageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.security.MessageDigest
import java.util.*

class PdfExporter(private val context: Context) {

    companion object {
        val PAGE_SIZE = com.itextpdf.kernel.geom.PageSize.A4
        const val MARGIN = 36f
    }

    private val db: HorizonDatabase = HorizonDatabase.getInstance(context)

    suspend fun generatePdf(
        startDate: Date? = null,
        endDate: Date? = null,
        contacts: List<Long> = emptyList(),
        outputFile: File
    ): String = withContext(Dispatchers.IO) {

        val writer = PdfWriter(outputFile)
        val pdf    = PdfDocument(writer)
        val doc    = Document(pdf, PAGE_SIZE).apply {
            setMargins(MARGIN, MARGIN, MARGIN, MARGIN)
        }

        val messages: List<MessageEntity> = if (contacts.isEmpty()) {
            if (startDate != null && endDate != null) {
                db.messageDao().getMonitoredInRange(startDate, endDate)
            } else {
                db.messageDao().getMonitoredPaged(limit = Int.MAX_VALUE, offset = 0)
            }
        } else {
            db.messageDao().getMonitoredPaged(limit = Int.MAX_VALUE, offset = 0)
        }

        addCoverPage(doc, messages.size, startDate, endDate)
        addMessagesTable(doc, messages)

        val pdfHash = computeHash(outputFile)
        addCustodyPage(doc, pdfHash)

        doc.close()
        pdfHash
    }

    private fun addCoverPage(doc: Document, messageCount: Int, start: Date?, end: Date?) {
        doc.add(Paragraph("HORIZON — CO-PARENTING MESSAGE EXPORT"))
        doc.add(AreaBreak())
        doc.add(Paragraph("Generated: ${Date()}"))
        doc.add(Paragraph("Date Range: ${start ?: "all"} to ${end ?: "all"}"))
        doc.add(Paragraph("Total Messages: $messageCount"))
        doc.add(Paragraph("Exported by: Horizon App"))
        doc.add(AreaBreak())
    }

    private fun addMessagesTable(doc: Document, messages: List<MessageEntity>) {
        val table = Table(UnitValue.createPercentArray(floatArrayOf(15f, 15f, 15f, 55f)))
            .setWidth(UnitValue.createPercentValue(100f))

        table.addHeaderCell(Paragraph("Timestamp"))
        table.addHeaderCell(Paragraph("Contact"))
        table.addHeaderCell(Paragraph("Direction"))
        table.addHeaderCell(Paragraph("Message"))

        messages.forEach { msg ->
            table.addCell(Paragraph(msg.date.toString()))
            table.addCell(Paragraph(msg.contactName ?: msg.address))
            table.addCell(Paragraph(if (msg.type == 1) "RECEIVED" else "SENT"))
            table.addCell(Paragraph(msg.body ?: "(no text)"))
        }

        doc.add(table)
    }

    private fun addCustodyPage(doc: Document, hash: String) {
        doc.add(AreaBreak())
        doc.add(Paragraph("CHAIN OF CUSTODY"))
        doc.add(Paragraph("This export was generated by Horizon App."))
        doc.add(Paragraph("SHA-256 hash of PDF: $hash"))
        doc.add(Paragraph("To verify integrity, recompute hash of this file and compare."))
    }

    private fun computeHash(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().use { fis ->
            val buffer = ByteArray(8192)
            var bytesRead: Int
            while (fis.read(buffer).also { bytesRead = it } != -1) {
                digest.update(buffer, 0, bytesRead)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}
